In [20]:
import json

json is a one of the python package used to decode and encode json data

In [21]:
import tweepy

with help of tweppy we can mine twitter data using API

In [22]:
import pandas as pd

pandas is a data visualization and manipulation library used in python

In [23]:
ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
ACCESS_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

ACCESS_TOKEN,ACCESS_SECRET,CONSUMER_KEY,CONSUMER_SECRET are API keys given by twitter for developers

In [24]:
username = "midasIIITD"

Here "username" is which user data we want to get from the twitter

In [25]:
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)

Here tweepy checks authentication of us by our CONSUMER_KEY,CONSUMER_SECRET

In [26]:
auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)

After authentication is done tweepy checks ACCESS_TOKEN and ACCESS_SECRET

In [27]:
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)

Here tweepy.API() assigns to api this says that the user has authenticated,the next parameters controls tweepy to blocking and they waits untill next API calls retuns

In [28]:
with open('midasIIITD_twitter_data.jsonl', 'w') as outfile: 
    for status in api.user_timeline(screen_name = username,count = 500):
        outfile.write(json.dumps(status._json)+"\n")

I had opened a json file named as midasIIITD_twitter_data.jsonl with write permission then I had used twitter timeline API to get tweets from the particular username and count defines number of tweets we want.Finally I'd dump the data I got from twitter to the file midasIIID_twitter_data.jsonl.

In [29]:
df = pd.read_json("midasIIITD_twitter_data.jsonl",lines = True)

  With help of pandas library I'd read data from midasIITD_twitter_data.jsonl by JSONLines and assigned it to df

In [30]:
df1 = pd.DataFrame(df,columns = ["text","created_at","favorite_count","retweet_count","media_url_https"])

With help of pandas library I'd created DataFrame and get specific columns from the DataFrame

In [31]:
df1

,text,created_at,favorite_count,retweet_count,media_url_https
0,RT @IIITDelhi: We are delighted to share that ...,2019-04-09 16:45:07,0,8,NaN
1,RT @Harvard: Professor Jelani Nelson founded A...,2019-04-09 05:04:27,0,35,NaN
2,RT @emnlp2019: For anyone interested in submit...,2019-04-09 05:04:11,0,12,NaN
3,RT @multimediaeval: Announcing the 2019 MediaE...,2019-04-08 19:38:09,0,15,NaN
4,"Many Congratulations to @midasIIITD student, S...",2019-04-08 07:08:12,14,2,NaN
5,@midasIIITD thanks all students who have appea...,2019-04-08 03:27:42,5,0,NaN
6,"@himanchalchandr Meanwhile, complete CV/NLP ta...",2019-04-07 14:17:29,0,0,NaN
7,@sayangdipto123 Submit as per the guideline ag...,2019-04-07 14:17:09,0,0,NaN
8,We request all students whose interview are sc...,2019-04-07 11:43:24,1,1,NaN
9,"Other queries: ""none of the Tweeter Apis give ...",2019-04-07 06:55:19,5,2,NaN
10,"Other queries: ""do we have to make two differe...",2019-04-07 06:53:38,4,1,NaN
11,"Other queries: ""If using Twitter api, it does ...",2019-04-07 05:32:27,6,1,NaN
12,Response to some queries asked by students on ...,2019-04-07 05:29:40,7,1,NaN
13,RT @kdnuggets: Top 8 #Free Must-Read #Books on...,2019-04-06 17:11:29,0,2,NaN
14,@nupur_baghel @PennDATS Congratulation @nupur_...,2019-04-06 16:43:27,18,3,NaN
15,We have emailed the task details to all candid...,2019-04-05 16:08:37,11,1,NaN
16,RT @rfpvjr: Our NAACL paper on polarization in...,2019-04-05 04:05:11,0,16,NaN
17,RT @kdnuggets: Effective Transfer Learning For...,2019-04-05 04:04:43,0,11,NaN
18,RT @stanfordnlp: What’s new in @Stanford CS224...,2019-04-03 18:31:53,0,59,NaN
19,RT @DeepMindAI: Today we're releasing a large-...,2019-04-03 17:04:32,0,870,NaN
20,RT @ylecun: Congratulations Jitendra Malik !\n...,2019-04-03 09:03:40,0,16,NaN
21,RT @IIITDelhi: Another chance to take admissio...,2019-04-03 07:46:02,0,4,NaN
22,Dear @midasIIITD internship candidates who hav...,2019-04-02 04:20:13,8,1,NaN
23,Looking forward to your paper submission to @I...,2019-04-02 02:44:54,5,1,NaN
24,RT @ngrams: Reproducibility in multimedia rese...,2019-04-02 02:35:44,0,7,NaN
25,Online application for https://t.co/DJFDrQsHZP...,2019-04-01 06:53:08,7,2,NaN
26,RT @ACMMM19: A final reminder of the Reproduci...,2019-03-31 10:21:24,0,10,NaN
27,RT @isarth23: Thanks for the support and help ...,2019-03-29 19:43:24,0,2,NaN
28,"Since SemEval-2019 will be held June 6-7, 2019...",2019-03-29 17:16:40,9,1,NaN
29,+@aggarwal_kartik.\nCongrats! Wish you many mo...,2019-03-29 17:04:30,2,0,NaN
...,...,...,...,...,...
170,RT @UniofOxford: In the final episode of serie...,2019-01-07 09:05:12,0,16,NaN
171,@ACMMM19: Call for Workshop Proposals \n\nDead...,2019-01-06 12:54:06,1,0,NaN
172,@ACMMM19: Call for Grand Challenge Proposals\n...,2019-01-06 04:29:25,1,0,NaN
173,"Since 1993, ACM Multimedia has been bringing t...",2019-01-06 04:09:54,5,1,NaN
174,@ACMMM19 is structured around four themes (alp...,2019-01-06 04:07:29,1,0,NaN
175,ACM Multimedia 2019: First Call for Papers/Cal...,2019-01-06 04:05:38,4,2,NaN
176,RT @ACMMM19: Happy new year! 2019 started with...,2019-01-03 06:14:05,0,2,NaN
177,You may follow @midasIIITD updates through fol...,2019-01-01 17:21:49,4,2,NaN
178,"Today, @midasIIITD completed one year at @IIIT...",2019-01-01 17:17:56,14,5,NaN
179,RT @debanjanbhucs: Happy anniversary to @midas...,2019-01-01 16:14:24,0,4,NaN
180,Two Research Assistant (RA) positions are stil...,2018-12-27 10:28:31,2,1,NaN
181,Positions for two Research Assistants (RA) are...,2018-12-27 09:59:06,5,3,NaN
182,RT @TCoolsIT: I wrote a blogpost on CoreNLP hi...,2018-12-27 02:33:58,0,12,NaN
183,@RatnRajiv delivered a research talk at the Ce...,2018-12-26 09:41:04,14,2,NaN
184,@midasIIITD look forward to work together. htt...,2018-12-25 04:15:15,1,0,NaN
185,"@the_dhumketu @punnibhai @Hitkul_, FYI. https:...",2018-12-25 03:00:21,2,1,NaN
186,RT @iiit_hyderabad: KCIS Distinguished Lecture...,2018-12-24 07:39:21,0,11,NaN
187,RT @StanfordAILab: Our latest blog post is out...,2018-12-21 03:50:39,0,32,NaN
188,"RT @medialab: In two new papers, @PratikShahPh...",2018-12-20 18:05:35,0,8,NaN
189,RT @RatnRajiv: Wonderful get together with our...,2018-12-20 06:14:52,0,3,NaN
190,@ACMMM19 is the premier international conferen...,2018-12-19 02:16:31,2,3,NaN
191,Feel free to contact us if you have any query ...,2018-12-18 14:42:27,3,2,NaN
192,@NilayShri @RatnRajiv @ACMMM19 Looking forward...,2018-12-18 14:27:12,3,0,NaN
193,"@midasIIITD head, Dr. @RatnRajiv appointed as ...",2018-12-18 14:15:32,12,5,NaN
194,@ACMMM19 @the_dhumketu fill the volunteer form...,2018-12-18 12:34:10,1,0,NaN
195,RT @ACMMM19: New in 2019! Volunteer to serve a...,2018-12-18 12:33:42,0,7,NaN
196,RT @IIITDelhi: Congratulations! authors Yaman ...,2018-12-18 04:38:35,0,3,NaN
197,Best wishes to @midasIIITD students @_himanshu...,2018-12-17 16:57:00,14,4,NaN
198,RT @MIT: Computer model could improve human-ma...,2018-12-17 15:05:44,0,20,NaN
199,RT @kdnuggets: Great @Wired interview with Geo...,2018-12-17 14:37:00,0,20,NaN